### ISSUE TITLE
FullWidthDetailsOverviewRowPresenter does not maintain its UI state

### ISSUE THREAD

**Issue by deepSymmetry** [googlesamples/androidtv-Leanback#95] opened 2017-09-11 01:11 UTC
The FullWidthDetailsOverviewRowPresenter on resume does not maintain its UI state. If the default state during initialization is set to STATE_HALF, hitting D-pad down changes state to STATE_FULL.

Suspend the app (goto home screen), resume the app and UI goes back to STATE_HALF. The resume causes row 0 to be selected and UI goes back to STATE_HALF. I have looked high and low and can't find a solution.

**Comment by benbaxter** [comment] 2017-09-11 17:59
Hello, I am trying to recreate this on an Nvidia Shield and the emulator and I am not seeing the state change that you mention. When debugging, the state is being maintained by the presenter based on the row selected. 

Can you clarify a bit more? What are you seeing and what are you expected? Which device are you using to test with?

I saw you posted on G+. To keep the communication simplified, let's continue the discussion here.

**Comment by deepSymmetry** [comment] 2017-09-11 19:23
Thanks for responding. I am testing on Nvidia Shield and I see that Google's Movie and TV app exhibit the same behavior on my setup. Right after posting this issue, I tried the latest leanback sample app on emulator and much to my delight, it maintains the state. However, my app exhibits the same behavior on emulator as it does on shield.

The Google's Movies & TV app is only wee bit faster but it does show the STATE_FULL for a split second and scrolls down to STATE_HALF.

While deep diving in leanback, I see that DetailsFragment -> onStart() -> verticalGridView().focus() leads to row 0 to be selected which leads to STATE_HALF.

I expected onSetDetailsOverviewRowStatus() to the hook but it didn't help since vertical grid view already scrolls by that time. I will double check with the latest leanback sample app on my real device and update this thread.

**Comment by deepSymmetry** [comment] 2017-09-11 19:32
I am using SDK version 25 and build tools 25.0.3. The latest sample app is at SDK 26 and I see some difference in the onStart() in DetailsFragment where it requests focus only if it doesn't already have it unlike 25. Allow me to try on the latest SDK and report back although I am always a little wary of trying the latest since it always brings some surprises and humongous QA effort.

**Comment by benbaxter** [comment] 2017-09-11 23:01
Are you using the v26 support library as well? 

If you can recreate the issue with this sample (using support lib 26), then you do not have to worry about any surprised or humongous QA effort while we track down the root cause. 😄 

If you want to downgrade this sample to use support library 25, playback will not work. You will need to comment out or remove the VideoPlayerGlue, LeanbackPlayerAdapter, and PlaybackFragment. Which should not be an issue since it sounds like you are only interested in the details fragment.

**Comment by deepSymmetry** [comment] 2017-09-12 20:36
Ok. The issue was introduced in Leanback 25.2.0. 26.0.1 does not have this issue. 26.0.1 fixed it by conditionally requesting verticalGridView().requestFocus().
Leanback 24 also did not have this issue because onStart() -> verticalGridView().requestFocus() was not present in it and was introduced only with 25 .  A ton of relief. 

Regarding player, I am not using the inbuilt playback infrastructure (Glue, Adapter etc). Its custom playback (controls etc) using player built over Exo player.

**Comment by deepSymmetry** [comment] 2017-09-12 20:38
That is the reason the leanback samples I have (at 24 and at 26) both did not exhibit this issue. I never had a chance to have the sample at level 25 which I am sure would have exhibited this issue.

**Comment by benbaxter** [comment] 2017-09-12 21:31
Awesome! It sounds like the issue has been resolved in 26.0.1 so I am going to close this issue since, sadly, there is nothing we can do about 25.2.0.

Re: player; It is a common approach to build an app with custom playback. I was just suggesting where, in this sample, the major changes are in 26 that won't compile when downgrading the sample to 25.

**Comment by deepSymmetry** [comment] 2017-09-12 22:04
I see. Thanks for your attention and help.

**Closed** 2017-09-13 23:10 UTC
