### ISSUE TITLE
Now Playing Icon on Card not Customizable

### ISSUE THREAD

**Issue by michaelrhughes** [googlesamples/androidtv-Leanback#73] opened 2016-07-26 16:27 UTC
I'm having an issue customizing the icon in the bottom right corner of the now playing card when a user hits the home button while watching a video on the Android TV Home screen.

I've tried to set 
metadata.putString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI, "android.resource://" + BuildConfig.APPLICATION_ID + "/drawable/android_header");

On the media session however it looks like it's not possible to change the icon on the Now Playing card. It seems to just pull directly from the application icon field. The issue here is that the icon is clearly greyscaled when this happens and the application icon I have has color in it. So I want to keep my current application icon for the playstore and have a different one for this now playing card.

I've also tried changing METADATA_KEY_DISPLAY_ICON to the bitmap directly and that doesn't seem to work. Any advice?

**Comment by Fleker** [comment] 2016-07-26 17:22
Have you looked at the logs to see if there was any issue applying this attribute?

Looking at [the documentation](https://developer.android.com/reference/android/media/MediaMetadata.html#METADATA_KEY_DISPLAY_ICON), 

> For the best results, Uris should use the content:// style and support EXTRA_SIZE for retrieving scaled artwork through openTypedAssetFileDescriptor(Uri, String, Bundle).

**Comment by michaelrhughes** [comment] 2016-07-26 20:26
Thanks for your response @Fleker!

I have attempted to do:

metadata.putString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI, "content://" + BuildConfig.APPLICATION_ID + "/drawable/android_header");

and 

metadata.putString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI, "android.content://" + BuildConfig.APPLICATION_ID + "/drawable/android_header");

and

metadata.putString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI, String.valueOf(getResources().getDrawable(R.drawable.android_header)));

Neither work.

I have also tried:

Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.android_header);
metadata.putBitmap(MediaMetadata.METADATA_KEY_DISPLAY_ICON, bitmap);

None seem to work. 

I found this stackoverflow problem of a user with the same issue:
https://stackoverflow.com/questions/29603038/android-tv-now-playing-card-icon

The only thing that seems to change it is by changing the icon of the app in the AndroidManifest. I look to see if changing my application's theme on launch with a theme that had a different icon would work but it didn't. I need to make this change because Android strips the color out of the icon and my icon does not look good but I want the playstore icon to be different.

Any ideas?

**Comment by Fleker** [comment] 2016-07-27 23:38
So I looked into this earlier and I can confirm your issue. The launcher seems to be taking the app icon and ignoring and sort of manual control. I'll try to contact someone and see why this is happening.

**Comment by Fleker** [comment] 2016-08-16 20:19
This issue is not related to the Leanback sample, but I'll leave it open while the launcher issue is being resolved.

**Comment by codingjeremy** [comment] 2019-09-27 18:26
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed by codingjeremy** 2019-09-27 18:26 UTC
Labels: bug, wontfix
