### ISSUE TITLE
Playback/Streaming does not work. 

### ISSUE THREAD

**Issue by timigod** [googlesamples/androidtv-Leanback#50] opened 2015-11-14 15:47 UTC
The sample app that google provides keeps giving me "can't play this video" and this stack trace:

```
11-14 10:45:29.852 8923-9263/com.example.android.tvleanback E/MediaPlayer: error (1, -38)
11-14 10:45:29.861 8923-9262/com.example.android.tvleanback E/MediaPlayer: error (1, -38)
11-14 10:45:29.861 8923-8923/com.example.android.tvleanback E/MediaPlayer: Error (1,-38)
11-14 10:45:29.861 8923-8923/com.example.android.tvleanback D/VideoView: Error: 1,-38
11-14 10:45:29.861 8923-8923/com.example.android.tvleanback E/MediaPlayer: stop called in state 0
11-14 10:45:29.861 8923-8923/com.example.android.tvleanback E/MediaPlayer: error (-38, 0)
11-14 10:45:29.940 8923-8923/com.example.android.tvleanback W/MediaPlayer: mediaplayer went away with unhanded events
```

I have spent hours trying to figure out what is wrong, to no avail. Not that this is my first foray into Android TV, so it's unlikely that I'd have been able to solve the issue.

**Comment by ryanseys** [comment] 2015-11-14 23:11
Are you using an emulator? If so, please ensure you're using an Android M
emulator as video playback only works in Android M emulator and above.

**Comment by timigod** [comment] 2015-11-15 09:12
Yes, I was using an emulator.
I tried using the Android M AVD for Android TV but for some reason, it refuses to connect to the internet, so I couldn't test video playback. (This isn't a problem for Android L Android TV AVDs).

So I took my testing to a Nexus 6P Genymotion Emulator in full screen. Still getting the same "can't play this video" pop up.

**Comment by timigod** [comment] 2015-11-16 17:08
Is there anything else I need to do/test/provide to help with this issue?

**Comment by timigod** [comment] 2015-11-21 11:03
Still waiting for any form of response or tip. :(

**Comment by ryanseys** [comment] 2015-11-22 21:16
Unfortunately, if your emulator refuses to connect to the internet that is beyond this library's control and beyond what assistance I can provide. I will file an issue internally to have someone look into emulator internet connectivity but please understand this is not an issue with this library but with the tooling around it. Please be patient as if this is an issue with the emulator, you will need wait until they release a fix. There is no change to this library that will fix the issue you are encountering unless we removed the need for network connectivity from this library which would be unrealistic. Thanks for your patience. I would encourage you to continue to seek help elsewhere on gaining connectivity to your emulator in the meantime.

**Comment by naddaf** [comment] 2015-11-22 21:22
I just created an emulator using API 23 and it could connect to internet with absolutely no issue, so the issue is local to your setup and not related to the emulator.

**Comment by naddaf** [comment] 2015-11-22 21:53
I should take it back; it doesn't have internet connectivity in M.

**Comment by ryanseys** [comment] 2015-11-22 22:09
Internal bug filed: 25831577

**Comment by timigod** [comment] 2015-11-29 08:15
I'd like to add that playback works on an Android 5.1 Nexus 10 emulator. But doesn't work on a 6.0, Nexus 6P emulator.

**Comment by IgorGanapolsky** [comment] 2015-12-11 05:11
I am having the same issue.  Just created a brand new Android_TV_1080p_Android_23 emulator from Android Studio 2.0.  All I get is the error toast: 
> Failed to load videos. Please check your network connection.

@ryanseys Did you test this repo on an emulator?

**Comment by atentis** [comment] 2016-02-07 01:06
I am having the same issue as @IgorGanapolsky. 

No internet when using emulator with the default project which has images and videos that load from the web.  I also tried adding code to hit my local api and that fails as well. For me all access to local network and internet do not work with android tv emulator sdk 22 and 23.

If I deploy this app to my Shield Android TV it connects to the web perfectly.

**Comment by ryanseys** [comment] 2016-02-08 18:20
Yes, this is an issue with the emulator and not our library. We're awaiting a fix for the emulator. I'll confirm this is fixed once I know that such a fix is publicly available.

**Comment by Cataalinn** [comment] 2016-02-22 10:26
Same problem with tv emulator. Waiting for fix!

**Comment by atentis** [comment] 2016-02-23 06:21
@ryanseys Thanks Ryan. My apologies as I see the emulator is not your responsibility. Thanks for keeping us posted!

**Comment by Cataalinn** [comment] 2016-03-02 08:50
Now it's working! Update to latest System images. Happy coding!

**Comment by ryanseys** [comment] 2016-03-02 17:54
@Cataalinn thanks for letting us know that it's now working for you :) I'll close this for now, but please let me know if you still encounter this issue.

**Closed by ryanseys** 2016-03-02 17:54 UTC
